# Generated by Django 3.0.6 on 2020-06-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='agent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
