# Generated by Django 3.0.6 on 2020-06-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200614_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='arquivado',
            field=models.BooleanField(verbose_name='Arquivado'),
        ),
    ]
